### PR TITLE
Fix for #1272

### PR DESCRIPTION
**Pull request by mattbell87**
Proposed additional check for #1272

### CODE REVIEW

**Comment by mattbell87** [comment]
Not sure what's going on here, it's saying 31 errors in 48 files yet I only changed 1 file.

**Comment by mattbell87** [comment]
I pulled a fresh copy from your repo, **npm install**, **grunt test** and it's still saying that, something odd is going on there. 

I did miss a semicolon on mine though I noticed, damn ASI.

**Comment by petetnt** [comment]
@mattbell87 This fixed #1272 for me, no more errors.

**Comment by mattbell87** [comment]
:+1:

**Comment by mattbell87** [comment]
@zaggino any idea what's causing the **grunt test** to fail? Updated linters maybe reporting previously unreported code issues?

**Comment by zaggino** [comment]
@mattbell87 not failing for me:
```
Zaggi@CO9QUQM MINGW64 ~/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git (master)
$ grunt test
Running "jshint:files" (jshint) task
>> 48 files lint free.

Running "jscs:src" (jscs) task
>> 48 files without code style errors.

Done, without errors.
```

**Comment by mattbell87** [comment]
Cheers! :)

Re: jshint have you tried doing `npm update` or `npm install --force ` to see if it's newer stuff that's causing Travis to fail?

**Comment by zaggino** [comment]
Yes, doing that makes the errors show now. I'll fix them later.

**Pull request merged**
