### PR TITLE
Added authentication to Clone dialog

### LINKED ISSUE #707: Clone pwd protected repositories
Seems like at the moment our extension doesn't support them...

### PR DESCRIPTION
**Pull request by mattbell87**
Fixes #707 and #1018

I added a new modal dialog js file and template for cloning. Closely based it on the Pull and Push dialogs in terms of code, but still looks familiar to the original Utils.askQuestion that handled cloning.

I replaced the Utils.askQuestion code with the new modal dialog in NoRepo.js. I looked at the Push/Pull code from Remotes.js and used the same methods and style. I removed the strings require as it's now handled in the modal dialog.

Added 1 line in the LESS file (just the ID of the modal) so that the input field is full length.

Linted everything with grunt jshint :). No errors or unhandled stuff.

brackets-git-clone-auth

### CODE REVIEW

**Comment by zaggino** [comment]
:+1:

**Comment by zaggino** [comment]
thanks for the PR, looks good

**Comment by zaggino** [comment]
Published this to [brackets-npm-registry](https://github.com/zaggino/brackets-npm-registry) as 0.15.0, brackets registry seems broken again so I'll try later there.

**Comment by mattbell87** [comment]
Cool thanks, I haven't tried the npm registry, might have to give it a spin!

**Comment by mattbell87** [comment]
Should we merge this in to your 1.x branch as well?

**Comment by zaggino** [comment]
1.x is a complete rewrite, i haven't had time to work on it for a while, maybe during christmas holidays ... anyway, it wouldn't be possible to merge this into it, i'll need to reimplement it again (1.x is done in react)

**Comment by mattbell87** [comment]
Ah I see no worries. I'll keep an eye on it and contribute if I can!

**Pull request merged**
