### PR TITLE
Fix gitignore filtering

### LINKED ISSUE #1038: Ignored folders starting with . aren't ignored
`.gitignore` is setup to ignore anything with say `*.nuget` in it.

Theses are ignored by git, and show as ignored in editors such as Atom. 

In your extension. Nothing that starts with `.` is ever shown as ignored.

If I add a character to the front like `a`. So I have `a.nuget` and update the `.gitignore` it works fine.

### PR DESCRIPTION
**Pull request by phillip-haydon**
Fixes #1038

1. Remove escaping of `[` and `]`
2. Change folder checks from 1 or more to 0 or more.

### CODE REVIEW

**Comment by MarcelGerber** [comment]
I noticed one slight issue with extended `.gitignore` syntax:
According to http://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#Ignoring-Files, `[0-9]` matches all the numbers, and so on. This isn't true here.

You can just remove the `-` from the list of characters to replace as it's only special in groups (`[]`).

**Comment by MarcelGerber** [comment]
Otherwise, it's fine.

**Comment by phillip-haydon** [comment]
Thanks @MarcelGerber I removed that too. :)

**Comment by zaggino** [comment]
Released in 0.14.27

**Comment by phillip-haydon** [comment]
<3 thanks a lot :D

**Pull request merged**
