### PR TITLE
Open bash terminal console fish shell #1003

### PR DESCRIPTION
**Pull request by quasivivo**
Simple command concatenation change to allow the Fish shell to open a terminal.

### CODE REVIEW

**Comment by zaggino** [comment]
@macbookandrew to review please

**Comment by macbookandrew** [comment]
@zaggino I don’t see any problem with it.

@quasivivo Does it work correctly with those changes only, or do we need to add "fish" to the list of shells on line 7 as well? The script loops through that list looking for a match against the terminal tab name.

**Comment by quasivivo** [comment]
@macbookandrew My default fish install doesn't appear to respect the tab_title set on lines 46-47, so adding "fish" to the line 7 list doesn't prevent a new tab from being opened each time.  I'm unfortunately not familiar enough with fish to fix that quickly.  These changes alone do correct the error in fish and put me in the project directory.

**Comment by quasivivo** [comment]
@macbookandrew I took another look at this and fish shell needs a temporary "fish_title" alias to allow the tab to be renamed.  Launching the shell works properly for me in bash and fish and a single iTerm tab persists for the repo between clicks with these changes.

**Pull request closed without merging**
