### PR TITLE
Commit counter checks current upstream, remote pick only refreshes counter

### LINKED ISSUE #1257: Invalid commit counter number.
Brackets Git v0.16.0 (started to reproduce after the update to v0.16.0)
Brackets 1.5

Invalid commit counter number. 

I have several remotes in my project (lets say 1 github + 1 custom hosted gitlab).
`origin` remote - github
`custom` remote - gitlab

I'm working in `custom` remote (not `origin`). My remote is ahead of `origin` by N commits.
Counter are showing the N number of non-pushed commits even if my working remote is `custom` and I've already pushed all these commits to it.

### PR DESCRIPTION
**Pull request by mattbell87**
Fixes #1257 and #1259

**Note**: While this works there is no checking to see whether branch or remote is undefined, so there are some errors on the console when working with remoteless repos. I need some advise on how to return `{ behind: -1, ahead: -1 }` if one of these are undefined.

### CODE REVIEW

**Comment by zaggino** [comment]
Oh, I've just made some changes to this too, you'll need to merge with master first, sorry.

**Comment by zaggino** [comment]
And you should also find the answer to your question in my code after you merge I think :)

**Comment by mattbell87** [comment]
Hahah yeah I had only synced within the last 15 min but there must have been changes since.

**Comment by mattbell87** [comment]
I'll fix the conflicts :+1:

**Comment by mattbell87** [comment]
Seems to be working nicely after fixing the conflict

**Comment by mattbell87** [comment]
Commited a fix to #1259 also

**Comment by zaggino** [comment]
Thanks, merged! :+1:

**Pull request merged**
