### PR TITLE
Improve i term

### PR DESCRIPTION
**Pull request by macbookandrew**
@zaggino Could you test this out? It’s not completely foolproof (yet… [it gets the correct window but not always the correct tab]) but it should do a better job of addressing #919.

### CODE REVIEW

**Comment by zaggino** [comment]
Works better than the current script, just one thing (as always) :smile: 

When I move a newly opened window to a split pane, its name changes from `2.git: zaggino.brackets-git (bash)` to `git: zaggino.brackets-git (bash)` and clicking on the terminal icon again the script is not able to detect terminals in split pane so it opens another window.

screen shot 2015-02-24 at 12 05 45

**Comment by macbookandrew** [comment]
I’ll keep working on it—may be a few days though. :smile:

**Comment by zaggino** [comment]
I can merge this one if you don't have time right now. It's still the best version we had so far anyway.

**Comment by macbookandrew** [comment]
Yeah, it’ll be a few days or a week maybe before I can spend much more time on it.

**Comment by zaggino** [comment]
Ok :+1:

**Pull request merged**
